FROM --platform=linux/amd64 python:3.8-slim

WORKDIR /app
RUN python3 -m venv /app/env

COPY ./requirements.txt /app/requirements.txt
RUN . /app/env/bin/activate
RUN pip install -r requirements.txt

COPY .env /app
COPY ./worker.py /app

CMD ["python3", "worker.py"]