FROM --platform=linux/amd64 python:3.8-slim

WORKDIR /app
RUN python3 -m venv /app/env

COPY ./requirements.txt /app/requirements.txt
RUN . /app/env/bin/activate
RUN pip install -r requirements.txt

COPY ./api.py /app
COPY ./dropbox_client.py /app
COPY ./parser.py /app
COPY ./search.py /app
COPY ./card.py /app
COPY ./date_test.py /app
COPY .env /app
COPY ./worker.py /app
COPY ./dropbox_client.py /app

CMD ["python3", "worker.py"]